version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 88d96412-8de1-450b-b1dd-1df28b2b6d17
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData2"
