version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 2903a46d-3f7e-48b0-bfbe-16e213356ae5
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData2"
