version: 1.0
app:
  instances:
    min: 1
    max: 1
  version: 7f5908cd-4bf7-4212-8eaa-b730d4decf3c
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
